### ISSUE TITLE
Adding item to Windows Firewall silently fails

### ISSUE THREAD

**Issue by ehawman** [mikeyhalla/MenuTools#3]
When attempting to add an exe to Windows Firewall via MenuTools, I get a 10:1 ratio of silent failures to successes. Tested with an actual executable (setup.exe) and then with an empty file (mytest.exe). It does work every once in a while, but I can't nail down why it does/doesn't.

Doesn't have anything to do with having the Windows Firewall window open.

Need a log or feedback of some kind to determine what's happening.

Image is the popup that flickers on the screen before it silently fails. Whatever has broken did so before this point.
![image](https://user-images.githubusercontent.com/52979227/94881891-2a51ad00-042c-11eb-91fd-bff384a5dcf7.png)

EDIT: Definitely has something to do with single files. Directory blocking works flawlessly.

**Comment by xCONFLiCTiONx** [comment]
Thank you for reporting this. I'll try to get on this in the morning and add some logging and give you a debug version to use. It's always nice to get some feedback from the community so feel free to keep me posted if you find anything on your end and i'll do my best to fix this issue quickly.

**Comment by xCONFLiCTiONx** [comment]
Okay, I just added a ton of changes including logging. I even changed the name to xMenuTools due to another program being named MenuTools so I decided to resolve that along with this change.

I did not have issues with the firewall blocking with the older version and looked through it and don't see any issues so I will need to see your log file once you have an error.

The log file is in "C:\ProgramData\Easy Logger".

Make sure to uninstall the old version before you install this one:

[xMenuTools.zip](https://github.com/xCONFLiCTiONx/xMenuTools/files/5319176/xMenuTools.zip)

**Comment by ehawman** [comment]
Wow, you do work quickly.

The very first time I tried it it failed. Then it worked on everything I threw at it for a while, _until I tried it on my E: drive_, then I got a failure, then a string of successes. Then I moved it to my L: drive, and it failed twice, worked a few, failed, worked, failed, back and forth. So that's where we're at. Log attached. Not sure if changing drives is actually doing anything or if it's just coincidence.
[xMenuTools.log](https://github.com/xCONFLiCTiONx/xMenuTools/files/5319345/xMenuTools.log)

But now there's something else. Any time you rename a file you get one of these (whether that rename is being applied to an existing file or if you're providing a name for a file created via right-click menu):
![image](https://user-images.githubusercontent.com/52979227/94948751-75f46d00-04a5-11eb-9842-ecb3466ce2dc.png)

Deleting any file yields this:
![image](https://user-images.githubusercontent.com/52979227/94949921-5eb67f00-04a7-11eb-9e85-6669935bd6ab.png)

None of these errors are making it to the log. I could start it as a separate issue if you want, but I feel like it's just a byproduct of the logging tools you put in for _this_ issue.

**Comment by xCONFLiCTiONx** [comment]
Thank you for providing this. I'll look into it and don't worry about creating a new issue.

**Comment by xCONFLiCTiONx** [comment]
Okay, I think this will solve both problems. I had a global exception catch and that was a bit much so I removed it and I set the form to inform when it's loaded before executing anything that requires the form to be loaded.

Again, make sure to uninstall the old version before installing this one.

REMOVED.
I found an issue and will have the next one up in a few minutes. Sorry for any inconvenience. 

I find it odd that these errors that are being reported lately don't happen to me. So strange... So thank you for reporting them!

**Comment by ehawman** [comment]
I can now add single files to the firewall reliably. Every single time. No problem.

The file rename/deletion issues remain. No logs in the log file, but upon deletion I still get this:
![image](https://user-images.githubusercontent.com/52979227/94956421-beb22300-04b1-11eb-8ceb-9aef8c6b3058.png)

>I find it odd that these errors that are being reported lately don't happen to me.

Maybe a different version of .NET or something? Also could be different settings. I don't have everything selected, just "Copy Path", "Copy Name", and "Block (All) with Windows Firewall". I am juuuuuuuust starting to learn C# so I can't really be of too much help.

As an aside, I think you should rename the Settings start menu shortcut to xMenuTools Settings, so it'll be easy to find without pinning.

It looks nice, IMO.
![image](https://user-images.githubusercontent.com/52979227/94957039-bb6b6700-04b2-11eb-80b2-679660077998.png)


EDIT: I see your edit. :)

**Comment by xCONFLiCTiONx** [comment]
Oh, yes, I also had to upgrade the .net version to 4.7.2. Sorry about that. I had to do that due to adding logging. Sigh.. So unprofessional of me. lol
This version SHOULD resolve the last issue.
[xMenuTools.zip](https://github.com/xCONFLiCTiONx/xMenuTools/files/5319660/xMenuTools.zip)

EDIT: 4.7.2 comes with Windows 10

**Comment by xCONFLiCTiONx** [comment]
I just added the feature request for shortcut name change. It will be in the next version. I'm just waiting to hear back to see if i need to make anymore changes. Thank you for being patient.

**Comment by ehawman** [comment]
That seems to do the trick! Everything is working 100% on my end. Nice work!

**Comment by xCONFLiCTiONx** [comment]
NICE! Thank you so much for helping me debug this. Make sure to download the release version here:
https://github.com/xCONFLiCTiONx/xMenuTools/releases

Uninstall the old version first.
