### ISSUE TITLE
How to unregister xMenuTools (later) from Windows Explorer?

### ISSUE THREAD

**Issue by tobwz** [mikeyhalla/MenuTools#5]
When I start xMenuTools the first time, then it registers itself immediately as Windows explorer context menu extension.

How can I un-register xMenuTools later?

I miss the opposite context menu option.

**Comment by xCONFLiCTiONx** [comment]
Just uninstall it from the programs and features menu. If you want more
control then visit https://github.com/dwmkerr/sharpshell
